# Generated by Django 4.2.7 on 2023-12-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('code', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PanierProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderation', models.FloatField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.panier')),
            ],
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('wilaya', models.CharField(max_length=255)),
                ('moughataa', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('gps_lat', models.FloatField()),
                ('gps_long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.pointdevente')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('price_unit', models.TextField()),
                ('code', models.TextField()),
                ('famille_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.familleproduit')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductFamily',
        ),
        migrations.AddField(
            model_name='price',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.produit'),
        ),
        migrations.AddField(
            model_name='panierproduit',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.price'),
        ),
    ]
