# Generated by Django 4.2.7 on 2023-12-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_familleproduit_panier_panierproduit_pointdevente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panierproduit',
            old_name='panier',
            new_name='panier_ID',
        ),
        migrations.RenameField(
            model_name='panierproduit',
            old_name='price',
            new_name='price_ID',
        ),
    ]
