# Generated by Django 4.2.7 on 2023-12-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_rename_panier_panierproduit_panier_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='point',
            new_name='point_ID',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='produit',
            new_name='produit_ID',
        ),
    ]
