# Generated by Django 4.2.7 on 2024-01-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0005_rename_famille_produit_produit_famille_produit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('annee_2016', models.FloatField()),
                ('annee_2017', models.FloatField()),
                ('annee_2018', models.FloatField()),
                ('annee_2019', models.FloatField()),
                ('annee_2020', models.FloatField()),
                ('annee_2021', models.FloatField()),
                ('annee_2022', models.FloatField()),
                ('annee_2023', models.FloatField()),
            ],
        ),
    ]
