
FROM python:3.8.18

RUN mkdir /app
WORKDIR /app

RUN pip install --upgrade pip
COPY requirement.txt .

RUN pip install -r requirement.txt 


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000
